/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;
import modele.*;
/**
 *
 * @author HP
 */
public class Profil extends javax.swing.JFrame {
    private User u;
    
    /**
     * Creates new form Profil
     */
    public Profil(User user) {
        initComponents();
        setLocationRelativeTo(this);
        this.u=user;
        afficherDonneesUtilisateur();
        
    }

    private Profil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
        private void afficherDonneesUtilisateur() {
        // Exemple d'utilisation des données de l'utilisateur
        nomprenom.setText(u.getPrenom());
        // Afficher d'autres données de l'utilisateur selon vos besoins
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backblue = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        nomprenom = new javax.swing.JLabel();
        peroamisbutton = new javax.swing.JButton();
        mesportsbutton = new javax.swing.JButton();
        rechamisbutton = new javax.swing.JButton();
        deconnexionbutton = new javax.swing.JLabel();
        exitCurseur = new javax.swing.JLabel();
        backgris1 = new javax.swing.JPanel();
        listamistext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listamis = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        demandeamis = new javax.swing.JList<>();
        demandemaistext = new javax.swing.JLabel();
        sportbutton3 = new javax.swing.JButton();
        sportbutton1 = new javax.swing.JButton();
        sportbutton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backblue.setBackground(new java.awt.Color(25, 149, 173));

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user (1).png"))); // NOI18N
        photo.setToolTipText("");

        nomprenom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nomprenom.setForeground(new java.awt.Color(255, 255, 255));
        nomprenom.setText("Nom Prenom");

        peroamisbutton.setText("Performances amis");
        peroamisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peroamisbuttonActionPerformed(evt);
            }
        });

        mesportsbutton.setText("Mes sports");
        mesportsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesportsbuttonActionPerformed(evt);
            }
        });

        rechamisbutton.setText("Recherche amis");
        rechamisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechamisbuttonActionPerformed(evt);
            }
        });

        deconnexionbutton.setForeground(new java.awt.Color(255, 255, 255));
        deconnexionbutton.setText("Déconnexion");

        exitCurseur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitCurseur.setForeground(new java.awt.Color(255, 255, 255));
        exitCurseur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitCurseur.setText("x");
        exitCurseur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitCurseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitCurseurMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backblueLayout = new javax.swing.GroupLayout(backblue);
        backblue.setLayout(backblueLayout);
        backblueLayout.setHorizontalGroup(
            backblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backblueLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(backblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backblueLayout.createSequentialGroup()
                        .addComponent(nomprenom)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backblueLayout.createSequentialGroup()
                        .addComponent(photo)
                        .addGroup(backblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backblueLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(mesportsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(peroamisbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(rechamisbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(deconnexionbutton)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backblueLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitCurseur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        backblueLayout.setVerticalGroup(
            backblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backblueLayout.createSequentialGroup()
                .addGroup(backblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backblueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backblueLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(backblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(peroamisbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rechamisbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mesportsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deconnexionbutton)))
                            .addComponent(photo)))
                    .addComponent(exitCurseur, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomprenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(backblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 180));

        backgris1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listamistext.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        listamistext.setText("Liste amis");
        backgris1.add(listamistext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        listamis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listamis);

        backgris1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 230, 240));

        demandeamis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(demandeamis);

        backgris1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 230, 240));

        demandemaistext.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        demandemaistext.setText("Demande amis");
        backgris1.add(demandemaistext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        getContentPane().add(backgris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 610));

        sportbutton3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        sportbutton3.setForeground(new java.awt.Color(17, 149, 173));
        sportbutton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock (1).png"))); // NOI18N
        sportbutton3.setText("Nom Sport");
        getContentPane().add(sportbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 380, 280));

        sportbutton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        sportbutton1.setForeground(new java.awt.Color(25, 149, 173));
        sportbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock (1).png"))); // NOI18N
        sportbutton1.setText("Nom Sport");
        getContentPane().add(sportbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 380, 280));

        sportbutton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        sportbutton2.setForeground(new java.awt.Color(25, 149, 173));
        sportbutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock (1).png"))); // NOI18N
        sportbutton2.setText("Nom Sport");
        getContentPane().add(sportbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 380, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peroamisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peroamisbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peroamisbuttonActionPerformed

    private void mesportsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesportsbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesportsbuttonActionPerformed

    private void rechamisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechamisbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechamisbuttonActionPerformed

    private void exitCurseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitCurseurMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitCurseurMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backblue;
    private javax.swing.JPanel backgris1;
    private javax.swing.JLabel deconnexionbutton;
    private javax.swing.JList<String> demandeamis;
    private javax.swing.JLabel demandemaistext;
    private javax.swing.JLabel exitCurseur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listamis;
    private javax.swing.JLabel listamistext;
    private javax.swing.JButton mesportsbutton;
    private javax.swing.JLabel nomprenom;
    private javax.swing.JButton peroamisbutton;
    private javax.swing.JLabel photo;
    private javax.swing.JButton rechamisbutton;
    private javax.swing.JButton sportbutton1;
    private javax.swing.JButton sportbutton2;
    private javax.swing.JButton sportbutton3;
    // End of variables declaration//GEN-END:variables
}
