/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JOptionPane;
import org.hibernate.Session;
import modele.*;
import org.hibernate.Transaction;
import vues.Profil;

/**
 *
 * @author Sabine
 */
public class Connexion extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Connexion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formSection = new javax.swing.JPanel();
        exitCurseur = new javax.swing.JLabel();
        connexionText = new javax.swing.JLabel();
        TextDeBienv = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pseudoIcon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mdpOublie = new javax.swing.JLabel();
        connexionbutton = new javax.swing.JButton();
        inscription = new javax.swing.JLabel();
        inscritText = new javax.swing.JLabel();
        mdp = new javax.swing.JPasswordField();
        pseudo = new javax.swing.JTextField();
        mdpIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(143, 143, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mask_group.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        formSection.setBackground(new java.awt.Color(25, 149, 173));
        formSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitCurseur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitCurseur.setForeground(new java.awt.Color(255, 255, 255));
        exitCurseur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitCurseur.setText("x");
        exitCurseur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitCurseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitCurseurMouseClicked(evt);
            }
        });
        formSection.add(exitCurseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        connexionText.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        connexionText.setForeground(new java.awt.Color(255, 255, 255));
        connexionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connexionText.setText("Connexion");
        formSection.add(connexionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 420, 41));

        TextDeBienv.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TextDeBienv.setForeground(new java.awt.Color(255, 255, 255));
        TextDeBienv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextDeBienv.setText("Bienvenue sur notre terrain !");
        formSection.add(TextDeBienv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 420, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 226, 255));
        jLabel5.setText("Pseudo");
        formSection.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 341, -1));

        pseudoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pseudoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_20px_1.png"))); // NOI18N
        formSection.add(pseudoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 40, 39));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 226, 255));
        jLabel8.setText("Mot de passe");
        formSection.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 341, -1));

        mdpOublie.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        mdpOublie.setForeground(new java.awt.Color(199, 226, 255));
        mdpOublie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mdpOublie.setText("Mot de passe oublié ?");
        mdpOublie.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formSection.add(mdpOublie, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 261, 121, 27));

        connexionbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        connexionbutton.setForeground(new java.awt.Color(25, 149, 173));
        connexionbutton.setText("Connexion");
        connexionbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        connexionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionbuttonActionPerformed(evt);
            }
        });
        formSection.add(connexionbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 306, 341, 40));

        inscription.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setText("S'inscrire");
        inscription.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formSection.add(inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 122, -1));

        inscritText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inscritText.setForeground(new java.awt.Color(199, 226, 255));
        inscritText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inscritText.setText("Pas encore inscrit ?");
        formSection.add(inscritText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 213, -1));

        mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdpActionPerformed(evt);
            }
        });
        formSection.add(mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 212, 290, 30));

        pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudoActionPerformed(evt);
            }
        });
        formSection.add(pseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 290, 30));

        mdpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock (1).png"))); // NOI18N
        formSection.add(mdpIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 30, 30));

        getContentPane().add(formSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));

        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitCurseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitCurseurMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitCurseurMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void connexionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionbuttonActionPerformed
        if(pseudo.getText().isEmpty()|| mdp.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "CHAMP OBLIGATOIRE");
            JOptionPane.showMessageDialog(this, "champ obligatioire", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }else{
            Session s = DBConnection.getSession();
            Transaction transaction = s.beginTransaction();
            User userExist = UserDataConnect.getUserByUsernameAndPassword(pseudo.getText(), mdp.getText());
            if(userExist!=null){
                JOptionPane.showMessageDialog(this, "Bienvenue\n"+userExist.getPrenom());
                Profil p = new Profil(userExist);
                p.setVisible(true);
                
                setVisible(false);
                      
            }else {
                JOptionPane.showMessageDialog(this, "Pseudo ou mot de passe inexistant !", "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_connexionbuttonActionPerformed

    private void mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdpActionPerformed

    private void pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextDeBienv;
    private javax.swing.JLabel connexionText;
    private javax.swing.JButton connexionbutton;
    private javax.swing.JLabel exitCurseur;
    private javax.swing.JPanel formSection;
    private javax.swing.JLabel inscription;
    private javax.swing.JLabel inscritText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JLabel mdpIcon;
    private javax.swing.JLabel mdpOublie;
    private javax.swing.JTextField pseudo;
    private javax.swing.JLabel pseudoIcon;
    // End of variables declaration//GEN-END:variables
}
