/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author Sabine
 */
public class Inscription extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Inscription() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        connexionText = new javax.swing.JLabel();
        formSection = new javax.swing.JPanel();
        exitCurseur = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inscriptionbutton = new javax.swing.JButton();
        inscription = new javax.swing.JLabel();
        inscritText = new javax.swing.JLabel();
        mdp = new javax.swing.JPasswordField();
        pseudo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pseudo1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mdp1 = new javax.swing.JPasswordField();
        mdp2 = new javax.swing.JPasswordField();
        selectsport = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cyclisme = new javax.swing.JCheckBox();
        course = new javax.swing.JCheckBox();
        tennis = new javax.swing.JCheckBox();
        natation = new javax.swing.JCheckBox();
        plancheavoile = new javax.swing.JCheckBox();
        halterophilie = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdiLogo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 500, 200));

        connexionText.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        connexionText.setForeground(new java.awt.Color(52, 58, 64));
        connexionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connexionText.setText("Créer un nouveau compte");
        jPanel1.add(connexionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 420, 41));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        formSection.setBackground(new java.awt.Color(25, 149, 173));
        formSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitCurseur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitCurseur.setForeground(new java.awt.Color(255, 255, 255));
        exitCurseur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitCurseur.setText("x");
        exitCurseur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitCurseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitCurseurMouseClicked(evt);
            }
        });
        formSection.add(exitCurseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 226, 255));
        jLabel5.setText("Nom");
        formSection.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 226, 255));
        jLabel8.setText("Mot de passe");
        formSection.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 341, -1));

        inscriptionbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inscriptionbutton.setForeground(new java.awt.Color(25, 149, 173));
        inscriptionbutton.setText("Inscription");
        inscriptionbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inscriptionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionbuttonActionPerformed(evt);
            }
        });
        formSection.add(inscriptionbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 341, 40));

        inscription.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setText("Se connecter");
        inscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        formSection.add(inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 122, -1));

        inscritText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inscritText.setForeground(new java.awt.Color(199, 226, 255));
        inscritText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inscritText.setText("Déja membre?");
        formSection.add(inscritText, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 213, -1));

        mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdpActionPerformed(evt);
            }
        });
        formSection.add(mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 340, 30));

        pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudoActionPerformed(evt);
            }
        });
        formSection.add(pseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(199, 226, 255));
        jLabel6.setText("Prénom");
        formSection.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 120, -1));

        pseudo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudo1ActionPerformed(evt);
            }
        });
        formSection.add(pseudo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 160, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(199, 226, 255));
        jLabel9.setText("Email");
        formSection.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 341, -1));

        mdp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdp1ActionPerformed(evt);
            }
        });
        formSection.add(mdp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 340, 30));

        mdp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdp2ActionPerformed(evt);
            }
        });
        formSection.add(mdp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 340, 30));

        selectsport.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        selectsport.setForeground(new java.awt.Color(199, 226, 255));
        selectsport.setText("Selectionner les sports");
        formSection.add(selectsport, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 341, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(199, 226, 255));
        jLabel11.setText("Pseudo");
        formSection.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 341, -1));

        cyclisme.setForeground(new java.awt.Color(255, 255, 255));
        cyclisme.setText("Cyclisme");
        cyclisme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyclismeActionPerformed(evt);
            }
        });
        formSection.add(cyclisme, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        course.setForeground(new java.awt.Color(255, 255, 255));
        course.setText("Course à pied");
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        formSection.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        tennis.setForeground(new java.awt.Color(255, 255, 255));
        tennis.setText("Tennis");
        tennis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tennisActionPerformed(evt);
            }
        });
        formSection.add(tennis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        natation.setForeground(new java.awt.Color(255, 255, 255));
        natation.setText("Natation");
        natation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natationActionPerformed(evt);
            }
        });
        formSection.add(natation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        plancheavoile.setForeground(new java.awt.Color(255, 255, 255));
        plancheavoile.setText("Planche à voile");
        plancheavoile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plancheavoileActionPerformed(evt);
            }
        });
        formSection.add(plancheavoile, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        halterophilie.setForeground(new java.awt.Color(255, 255, 255));
        halterophilie.setText("Haltérophilie");
        halterophilie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halterophilieActionPerformed(evt);
            }
        });
        formSection.add(halterophilie, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        getContentPane().add(formSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));

        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitCurseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitCurseurMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitCurseurMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void inscriptionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscriptionbuttonActionPerformed

    private void mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdpActionPerformed

    private void pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudoActionPerformed

    private void pseudo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudo1ActionPerformed

    private void mdp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdp1ActionPerformed

    private void mdp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdp2ActionPerformed

    private void cyclismeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyclismeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cyclismeActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void tennisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tennisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tennisActionPerformed

    private void natationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_natationActionPerformed

    private void plancheavoileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plancheavoileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plancheavoileActionPerformed

    private void halterophilieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halterophilieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halterophilieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connexionText;
    private javax.swing.JCheckBox course;
    private javax.swing.JCheckBox cyclisme;
    private javax.swing.JLabel exitCurseur;
    private javax.swing.JPanel formSection;
    private javax.swing.JCheckBox halterophilie;
    private javax.swing.JLabel inscription;
    private javax.swing.JButton inscriptionbutton;
    private javax.swing.JLabel inscritText;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JPasswordField mdp1;
    private javax.swing.JPasswordField mdp2;
    private javax.swing.JCheckBox natation;
    private javax.swing.JCheckBox plancheavoile;
    private javax.swing.JTextField pseudo;
    private javax.swing.JTextField pseudo1;
    private javax.swing.JLabel selectsport;
    private javax.swing.JCheckBox tennis;
    // End of variables declaration//GEN-END:variables
}
